### ISSUE TITLE
Add blurb which tell what this site is about!

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-licensedb#13]
Nothing on the web site tell what this site contains

**Comment by AyanSinhaMahapatra** [comment]
This was originally added in https://github.com/nexB/scancode-licensedb/pull/23, removed by mistake and again added back in https://github.com/nexB/scancode-toolkit/pull/3202

**Comment by AyanSinhaMahapatra** [comment]
This is now in https://scancode-licensedb.aboutcode.org/help.html, closing this.
