### ISSUE TITLE
Deprecated license IDs have been removed from `index.json`

### ISSUE THREAD

**Issue by fviernau** [nexB/scancode-licensedb#35]
See https://scancode-licensedb.aboutcode.org/index.json.

Expected: Deprecated license IDs should be contained in the index.

**Comment by fviernau** [comment]
Thanks @AyanSinhaMahapatra !

Seems I was wrong assuming that the removed license are all deprecated.
Anyhow, find below the full list of licenses I've been missing in the `index.json`.
I presume, no license should be ever removed due to deprecation mechanisms?

``` 
LicenseRef-scancode-fsf-unlimited-no-warranty
LicenseRef-scancode-graphics-gems
LicenseRef-scancode-libpbm
LicenseRef-scancode-markus-kuhn-license
LicenseRef-scancode-martin-birgmeier
LicenseRef-scancode-minpack
LicenseRef-scancode-mit-addition
LicenseRef-scancode-ms-lpl
LicenseRef-scancode-nicta-psl
LicenseRef-scancode-openpbs-2.3
LicenseRef-scancode-osf-1990
LicenseRef-scancode-snprintf
LicenseRef-scancode-sunpro
LicenseRef-scancode-thor-pl
LicenseRef-scancode-x11-bitstream
LicenseRef-scancode-MPL-2.0-no-copyleft-exception
```

**Comment by AyanSinhaMahapatra** [comment]
> They recently got an SPDX license ID assigned while I was searching for LicenseRef-*

Yes, that's the issue.

The ScanCode LicenseDB is keyed by the scancode `license_key`, which we can guarantee will never change. But that is not the case with SPDX license keys. Just curious, why do you track these by their `spdx_license_key` and not the `license_key`? We will anyway have the corresponding SPDX license keys for that 

Also note that we preserve these old SPDX license keys in `other_spdx_license_keys` like this [here](
https://github.com/nexB/scancode-toolkit/blob/8556240cc780c9a81307c61682e2ef8ebf6e7793/src/licensedcode/data/licenses/snprintf.LICENSE#L9), but this is not an attribute on the index.json (But it is present in the individual JSON like [here](https://scancode-licensedb.aboutcode.org/snprintf.json)

**Comment by AyanSinhaMahapatra** [comment]
> So, this issue is indeed invalid. Sorry for the noise.

Closing this btw.
