### ISSUE TITLE
Upgrade to SPDX License List v3.21

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-licensedb#37]
It's time to synchronize with the latest SPDX licenses. 

The version 3.21 release of the SPDX license list is now tagged and live at https://spdx.org/licenses.

28 new licenses / exceptions were added to the list:

1.	Asterisk-exception
2.	ASWF-Digital-Assets-1.0
3.	ASWF-Digital-Assets-1.1
4.	Autoconf-exception-macro
5.	Boehm-GC
6.	CC-BY-SA-3.0-IGO
7.	cryptsetup-OpenSSL-exception
8.	dtoa
9.	GPL-3.0-interface-exception
10.	Inner-Net-2.0
11.	Latex2e-translated-notice
12.	libpri-OpenH323-exception
13.	Linux-man-pages-1-para
14.	Linux-man-pages-copyleft-2-para
15.	Linux-man-pages-copyleft-var
16.	LLGPL
17.	metamail
18.	MIT-Festival
19.	NIST-Software
20.	OLFL-1.3
21.	OPL-UK-3.0
22.	SGP4
23.	TermReadKey
24.	UnixCrypt
25.	vsftpd-openssl-exception
26.	Widget-Workshop
27.	Xdebug-1.03
28.	Xfig

The release also included schema and technical updates, adjustments to markup for many licenses, updates and expansions to documentation, and various other changes.

More details can be found in the release notes at https://github.com/spdx/license-list-XML/releases/tag/v3.21.

**Comment by AyanSinhaMahapatra** [comment]
This is now available in licenseDB, see https://scancode-licensedb.aboutcode.org/asterisk-exception.html for example.

**Comment by AyanSinhaMahapatra** [comment]
Closing as this (and the next version 3.22) was completed.
