### ISSUE TITLE
Use https links wherever possible

### ISSUE THREAD

**Issue by sbs2001** [nexB/scancode-licensedb#4]
See https://scancode-licensedb.aboutcode.org/gpl-2.0-plus

It has a reference to http://opensource.org/licenses/GPL-2.0 while https://opensource.org/licenses/GPL-2.0 is also valid .

**Comment by tdruez** [comment]
https://scancode-licensedb.aboutcode.org/gpl-2.0-plus has actually references to both:

- http://www.opensource.org/licenses/GPL-2.0
- https://opensource.org/licenses/GPL-2.0

Also, note that the data exposed in the licensedb is directly generated from the scancode-toolkit data. In case you notice a data issue, you can use the "edit data" link in the license details view to submit a correction.
