### ISSUE TITLE
Adding SoftFoat License for Release 2c to the database

### ISSUE THREAD

**Issue by LeChasseur** [nexB/scancode-licensedb#46]
Older licenses of Softfloat do not provide for a distribution right (LicenseRef-scancode-softfloat-2.0). This was corrected with Release 2c (http://www.jhauser.us/arithmetic/SoftFloat.html). The license text is available in the README of http://www.jhauser.us/arithmetic/SoftFloat-2c.zip and at https://github.com/stffrdhrn/berkeley-softfloat-2?search=1
Would be great to add that to the database. LicenseRef-scancode-softfloat-2.0c might work as an identifier.

**Comment by pombredanne** [comment]
Thanks! ... @DennisClark  FYI

**Comment by DennisClark** [comment]
The new license will be synchronized from scancode-toolkit when this issue is completed: 
https://github.com/nexB/scancode-toolkit/issues/3564

**Comment by AyanSinhaMahapatra** [comment]
This is added with https://github.com/nexB/scancode-toolkit/pull/3586 and is now available at: https://scancode-licensedb.aboutcode.org/softfloat-2c.html
