### ISSUE TITLE
Upgrade to SPDX License List v3.23

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-licensedb#49]
It's time to synchronize with the latest SPDX licenses.

The version 3.23 release of the SPDX license list is now tagged and live at https://spdx.org/licenses.

See https://lists.spdx.org/g/Spdx-legal/message/3509 

43 new licenses / exceptions were added to the list:

1. Adobe-Display-PostScript
2. AML-glslang
3. bcrypt-Solar-Designer
4. Bison-exception-1.24
5. Brian-Gladman-2-Clause
6. BSD-2-Clause-Darwin
7. BSD-3-Clause-acpica
8. BSD-Source-beginning-file
9. BSD-Systemics-W3Works
10. Caldera-no-preamble
11. CC-BY-3.0-AU
12. CMU-Mach-nodoc
13. DEC-3-Clause
14. DRL-1.1
15. fmt-exception
16. FSFAP-no-warranty-disclaimer
17. GCR-docs
18. Gmsh-exception
19. GNOME-examples-exception
20. gtkbook
21. hdparm
22. HPND-Fenneberg-Livingston
23. HPND-INRIA-IMAG
24. HPND-Kevlin-Henney
25. HPND-MIT-disclaimer
26. HPND-sell-MIT-disclaimer-xserver
27. ISC-Veillard
28. LPD-document
29. Mackerras-3-Clause
30. Mackerras-3-Clause-acknowledgment
31. mailprio
32. OpenSSL-standalone
33. OpenVision
34. Pixar
35. radvd
36. SAX-PD-2.0
37. softSurfer
38. SSLeay-standalone
39. Sun-PPP
40. TGPPL-1.0
41. UMich-Merit
42. Unicode-3.0
43. xkeyboard-config-Zinoviev

The release also included adjustments to markup for many licenses and updates to documentation.

More details can be found in the release notes at https://github.com/spdx/license-list-XML/releases/tag/v3.23.

**Comment by DennisClark** [comment]
This link might be useful as well:

https://github.com/spdx/license-list-XML/compare/v3.22...v3.23

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra note that most of these likely exist in ScanCode already. As it happens the SPDX legal team seems to like inventing new ids and would probably be better of to reuse ours. We can manage either way.

**Comment by AyanSinhaMahapatra** [comment]
This is now available at https://scancode-licensedb.aboutcode.org/
Closing!
