### ISSUE TITLE
Wrap links in anchor tags

### ISSUE THREAD

**Issue by sbs2001** [nexB/scancode-licensedb#5]
At https://scancode-licensedb.aboutcode.org/gpl-2.0-plus

Consider  making `other_urls` and `text_urls`  clickable .

**Comment by tdruez** [comment]
@sbs2001 all the URLs are now displayed as links.

Also, the details UI was improved for better readability:

<img width="927" alt="Screen Shot 2021-06-03 at 12 21 51 PM" src="https://user-images.githubusercontent.com/489057/120630131-ce31a380-c466-11eb-8195-86454a95abca.png">
