### ISSUE TITLE
data issue with key=amazon-sl

### ISSUE THREAD

**Issue by DennisClark** [nexB/scancode-licensedb#51]
The entry in the LicenseDB for key=amazon-sl contains the following values that seem to be a mistake:

spdx_license_key LicenseRef-.amazon.com.-AmznSL-1.0
other_spdx_license_keys LicenseRef-scancode-amazon-sl

It seems to me that the key/value pairs got switched around and actually ought to be

spdx_license_key LicenseRef-scancode-amazon-sl
other_spdx_license_keys LicenseRef-.amazon.com.-AmznSL-1.0

Actually the "other" key might simply be incorrect altogether.

@AyanSinhaMahapatra Please correct this when you have time, thanks.

**Comment by pombredanne** [comment]
Actually the weird SPDX identifier is the way Amazon likes to name this license:
"LicenseRef-.amazon.com.-AmznSL-1.0"
- https://github.com/alexa/avs-device-sdk/blob/master/InterruptModel/include/InterruptModel/InterruptModel.h#L4
- https://github.com/search?q="LicenseRef-.amazon.com.-AmznSL-1.0"&type=code

**Comment by pombredanne** [comment]
We can switch if you prefer, and track as a secondary license, but this may come up as a surprise.

**Comment by DennisClark** [comment]
no problem, as long as this was intentional.  Closing.

**Comment by mjherzog** [comment]
I recall that Amazon was a strong proponent of a DNS-based scheme for LicenseRef.
