### ISSUE TITLE
Publish new version?

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-licensedb#6]
The public version at https://scancode-licensedb.aboutcode.org may be out of date 
`Generated with ScanCode toolkit 21.2.9 on Feb 10, 2021.`
and the current version is 21.3.31

**Comment by tdruez** [comment]
New version published.
Ideally, we should automatically trigger the update of the licensedb on the publication of a new scancode-toolkit release.
Maybe through a GitHub action?

**Comment by pombredanne** [comment]
Yes, some action or azure would work well
