### ISSUE TITLE
Expose SPDX license key and is_exception in the index.json

### ISSUE THREAD

**Issue by pombredanne** [nexB/scancode-licensedb#7]
In order to help validating SPDX license expressions, I would like to have these extra attributes:

1. spdx_license_key
2. other_spdx_license_keys
3. is_exception

This way I can create a list of license_expression.LicenseSymbol objects and validate easily. This is going to be useful for https://github.com/nexB/license-expression/issues/56

**Comment by tdruez** [comment]
Deployed. See https://scancode-licensedb.aboutcode.org/index.json
